use serde::{Deserialize, Serialize};

use crate::capability::Capability;

// Validation bounds matching contracts/http-api.md
pub const MAX_TOKENS_DEFAULT: u32 = 512;
pub const MAX_TOKENS_LIMIT: u32 = 4096;
pub const TEMPERATURE_DEFAULT: f32 = 0.7;
pub const TEMPERATURE_MIN: f32 = 0.0;
pub const TEMPERATURE_MAX: f32 = 2.0;

// --- Request types ---

/// OpenAI-style message unit. role is "system", "user", or "assistant".
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub role: String,
    pub content: MessageContent,
}

/// Message content is either a plain string (Chat/Code) or a parts array (Caption).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    Text(String),
    Parts(Vec<ContentPart>),
}

/// A single content part in a multimodal message.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentPart {
    Text { text: String },
    ImageUrl { image_url: ImageUrl },
}

/// Inline image reference for Caption requests.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageUrl {
    /// data URI: "data:image/jpeg;base64,<base64-bytes>"
    pub url: String,
}

/// The request the Rust client assembles before sending to Triton.
/// This is NOT directly serialized to the wire — client.rs maps it to
/// ChatCompletionRequest for the actual HTTP body.
#[derive(Debug, Clone)]
pub struct InferenceRequest {
    /// UUID v4, generated by the client per request.
    pub id: String,
    /// Conversation history in OpenAI format.
    pub messages: Vec<Message>,
    /// Base64-encoded image bytes. Presence triggers Caption routing.
    pub image: Option<String>,
    /// Optional routing hint. "code" in this field triggers Code routing.
    pub system_hint: Option<String>,
    /// Max tokens to generate. Defaults to MAX_TOKENS_DEFAULT.
    pub max_tokens: Option<u32>,
    /// Sampling temperature [0.0–2.0]. Defaults to TEMPERATURE_DEFAULT.
    pub temperature: Option<f32>,
}

// --- Wire types (serialized to/from HTTP) ---

/// OpenAI-compatible chat completion request body, as sent on the wire to Triton.
#[derive(Debug, Serialize)]
pub struct ChatCompletionRequest {
    pub model: String,
    pub messages: Vec<Message>,
    pub max_tokens: u32,
    pub temperature: f32,
    pub stream: bool,
}

/// OpenAI-compatible chat completion response, as received from Triton.
#[derive(Debug, Deserialize)]
pub struct ChatCompletionResponse {
    pub id: String,
    pub model: String,
    pub choices: Vec<Choice>,
    pub usage: Option<Usage>,
}

#[derive(Debug, Deserialize)]
pub struct Choice {
    pub message: AssistantMessage,
    pub finish_reason: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct AssistantMessage {
    pub role: String,
    pub content: String,
}

#[derive(Debug, Deserialize)]
pub struct Usage {
    pub prompt_tokens: Option<u32>,
    pub completion_tokens: Option<u32>,
    pub total_tokens: Option<u32>,
}

/// The structured result returned to the caller after an inference request.
#[derive(Debug)]
pub struct InferenceResponse {
    /// Echoed from InferenceRequest.id.
    pub request_id: String,
    /// Capability that was resolved and used for this request.
    pub capability: Capability,
    /// Generated text content from the model.
    pub content: String,
    /// Triton model identifier echoed from the endpoint response.
    pub model_id: String,
    /// Tokens consumed by the input prompt (from endpoint usage field).
    pub prompt_tokens: Option<u32>,
    /// Tokens in the generated output (from endpoint usage field).
    pub completion_tokens: Option<u32>,
    /// Wall-clock request latency measured by the client.
    pub latency_ms: u64,
}

/// Response from GET /v1/models, used for the startup probe.
#[derive(Debug, Deserialize)]
pub struct ModelsResponse {
    pub data: Vec<ModelInfo>,
}

#[derive(Debug, Deserialize)]
pub struct ModelInfo {
    pub id: String,
}
